service: average-hours

configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  deploymentBucket:
    # Provisioned by grrr-amsterdam/hosting repo
    name: "serverless.deployments.grrr"
  tags:
    client: "average_hours"
    ManagedBy: Serverless
    Project: "Average hours"

  stage: prod
  region: eu-central-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
          Resource: "arn:aws:ssm:eu-central-1:308691726112:parameter/slack_app_average_hours"

plugins:
  - serverless-plugin-resource-tagging

layers:
  cache:
    path: ./lambda-cache-layer
    name: Cache_Extension_Layer
    compatibleRuntimes:
      - nodejs12.x
      - python3.8
      - java11
      - go1.x

functions:
  slack:
    handler: handler.slack
    timeout: 4
    environment:
      CACHE_EXTENSION_INIT_STARTUP: true
    layers:
      - { Ref: CacheLambdaLayer }
    events:
      - httpApi:
          path: /average-hours
          method: post

resources:
  extensions:
    SlackLogGroup:
      Properties:
        RetentionInDays: "30"
