service: average-hours

configValidationMode: error

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  deploymentBucket:
    # Provisioned by grrr-amsterdam/hosting repo
    name: "serverless.deployments.grrr"
  tags:
    client: "average_hours"
    ManagedBy: Serverless
    Project: "Average hours"

  stage: prod
  region: eu-central-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
          Resource: "arn:aws:ssm:eu-central-1:308691726112:parameter/slack_app_average_hours"
        - Effect: "Allow"
          Action:
            - "kms:Decrypt"
          Resource: "arn:aws:kms:eu-central-1:308691726112:key/4acb0f04-da62-4a0d-b15d-d1b8843cf18e"

functions:
  slack:
    handler: handler.slack
    timeout: 4
    environment:
      PARAMETERS_SECRETS_EXTENSION_HTTP_PORT: 2773
    layers:
      - "arn:aws:lambda:eu-central-1:187925254637:layer:AWS-Parameters-and-Secrets-Lambda-Extension:2"
    events:
      - httpApi:
          path: /average-hours
          method: post

resources:
  extensions:
    SlackLogGroup:
      Properties:
        RetentionInDays: "14"
