service: average-hours

frameworkVersion: "2"
configValidationMode: error

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  logRetentionInDays: 7

  stage: prod
  region: eu-central-1

  iam:
    role:
      statements:
        - Effect: "Allow"
          Action:
            - "ssm:GetParameter"
          Resource: "arn:aws:ssm:eu-central-1:308691726112:parameter/slack_app_average_hours"

layers:
  cache:
    path: ./lambda-cache-layer
    name: Cache_Extension_Layer
    compatibleRuntimes:
      - nodejs12.x
      - python3.8
      - java11
      - go1.x

functions:
  slack:
    handler: handler.slack
    timeout: 4
    environment:
      CACHE_EXTENSION_INIT_STARTUP: true
    layers:
      - { Ref: CacheLambdaLayer }
    events:
      - httpApi:
          path: /average-hours
          method: post
