name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: arn:aws:iam::308691726112:role/deploy-average-hours
          aws-region: eu-central-1

      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: "npm"

      - name: Dependencies
        run: npm install --production

      - name: Deploy
        run: npx serverless deploy
